#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

COMPOSE_BIN="${COMPOSE_BIN:-docker compose}"
COMPOSE_FILE="$ROOT_DIR/compose.yaml"
if [[ ! -f "$COMPOSE_FILE" ]]; then
  echo "Missing $COMPOSE_FILE. Pull the dev branch before deploying." >&2
  exit 1
fi
COMPOSE=($COMPOSE_BIN -f "$COMPOSE_FILE" --project-directory "$ROOT_DIR")
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@admin.com}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-}"
APP_URL="${APP_URL:-http://localhost:7001}"
FORCE_INSTALL="${FORCE_INSTALL:-0}"

set_env() {
  local key="$1"
  local value="$2"
  local tmp
  touch .env
  tmp="$(mktemp)"
  awk -v key="$key" -v value="$value" '
    BEGIN { updated = 0 }
    $0 ~ "^" key "=" { print key "=" value; updated = 1; next }
    { print }
    END { if (!updated) print key "=" value }
  ' .env > "$tmp"
  mv "$tmp" .env
}

configure_runtime_env() {
  set_env APP_URL "$APP_URL"
  set_env DB_CONNECTION mysql
  set_env DB_HOST mysql
  set_env DB_PORT 3306
  set_env DB_DATABASE xboard
  set_env DB_USERNAME root
  set_env DB_PASSWORD xboard123
  set_env CACHE_DRIVER redis
  set_env QUEUE_CONNECTION redis
  set_env REDIS_HOST redis
  set_env REDIS_PORT 6379
  set_env REDIS_PASSWORD null
}

echo "==> Preparing .env"
if [[ ! -f .env ]]; then
  cp .env.example .env
fi
echo "==> Using compose file: $COMPOSE_FILE"

configure_runtime_env

echo "==> Starting database and cache"
"${COMPOSE[@]}" up -d mysql redis

echo "==> Waiting for database"
db_ready=0
for _ in {1..60}; do
  if "${COMPOSE[@]}" exec -T mysql mysqladmin ping -h 127.0.0.1 -uroot -pxboard123 --silent >/dev/null 2>&1; then
    db_ready=1
    break
  fi
  sleep 2
done
if [[ "$db_ready" != "1" ]]; then
  echo "MySQL did not become ready in time." >&2
  "${COMPOSE[@]}" logs --tail=80 mysql >&2 || true
  exit 1
fi

echo "==> Waiting for Redis"
redis_ready=0
for _ in {1..30}; do
  if "${COMPOSE[@]}" exec -T redis redis-cli ping >/dev/null 2>&1; then
    redis_ready=1
    break
  fi
  sleep 1
done
if [[ "$redis_ready" != "1" ]]; then
  echo "Redis did not become ready in time." >&2
  "${COMPOSE[@]}" logs --tail=80 redis >&2 || true
  exit 1
fi

if [[ "$FORCE_INSTALL" == "1" ]] || ! grep -q '^INSTALLED=true' .env 2>/dev/null; then
  echo "==> Installing Xboard with Docker Compose"
  "${COMPOSE[@]}" run --rm \
    -e ENABLE_REDIS=true \
    -e ADMIN_ACCOUNT="$ADMIN_EMAIL" \
    xboard php artisan xboard:install
  configure_runtime_env
fi

echo "==> Starting services"
"${COMPOSE[@]}" up -d

echo "==> Clearing caches"
"${COMPOSE[@]}" exec -T xboard php artisan optimize:clear >/dev/null || true

if [[ -n "$ADMIN_PASSWORD" ]]; then
  echo "==> Applying admin account password"
  ADMIN_EMAIL="$ADMIN_EMAIL" ADMIN_PASSWORD="$ADMIN_PASSWORD" "$ROOT_DIR/scripts/init-admin.sh"
fi

echo "==> Restarting Xboard with fresh config"
"${COMPOSE[@]}" restart xboard >/dev/null

echo
echo "Done."
echo "Panel: $APP_URL"
echo "Admin email: $ADMIN_EMAIL"
if [[ -z "$ADMIN_PASSWORD" ]]; then
  echo "Admin password: generated by xboard:install; check install output or run scripts/init-admin.sh"
fi
