#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

COMPOSE_BIN="${COMPOSE_BIN:-docker compose}"
COMPOSE_FILE="${COMPOSE_FILE:-}"
if [[ -z "$COMPOSE_FILE" ]]; then
  if [[ -f "$ROOT_DIR/docker-compose.yml" ]]; then
    COMPOSE_FILE="$ROOT_DIR/docker-compose.yml"
  elif [[ -f "$ROOT_DIR/compose.sample.yaml" ]]; then
    COMPOSE_FILE="$ROOT_DIR/compose.sample.yaml"
  else
    echo "No compose file found. Expected docker-compose.yml or compose.sample.yaml." >&2
    exit 1
  fi
fi
COMPOSE=($COMPOSE_BIN -f "$COMPOSE_FILE" --project-directory "$ROOT_DIR")
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@admin.com}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-}"
APP_URL="${APP_URL:-http://localhost:7001}"

set_env() {
  local key="$1"
  local value="$2"
  local tmp
  touch .env
  tmp="$(mktemp)"
  awk -v key="$key" -v value="$value" '
    BEGIN { updated = 0 }
    $0 ~ "^" key "=" { print key "=" value; updated = 1; next }
    { print }
    END { if (!updated) print key "=" value }
  ' .env > "$tmp"
  mv "$tmp" .env
}

echo "==> Preparing .env"
if [[ ! -f .env ]]; then
  cp .env.example .env
fi
echo "==> Using compose file: $COMPOSE_FILE"

if ! grep -q '^INSTALLED=true' .env 2>/dev/null; then
  echo "==> Installing Xboard with Docker Compose"
  "${COMPOSE[@]}" run --rm \
    -e ENABLE_SQLITE=true \
    -e ENABLE_REDIS=true \
    -e ADMIN_ACCOUNT="$ADMIN_EMAIL" \
    xboard php artisan xboard:install
fi

set_env APP_URL "$APP_URL"

echo "==> Starting services"
"${COMPOSE[@]}" up -d

echo "==> Clearing caches"
"${COMPOSE[@]}" exec -T xboard php artisan optimize:clear >/dev/null || true

if [[ -n "$ADMIN_PASSWORD" ]]; then
  echo "==> Applying admin account password"
  ADMIN_EMAIL="$ADMIN_EMAIL" ADMIN_PASSWORD="$ADMIN_PASSWORD" "$ROOT_DIR/scripts/init-admin.sh"
fi

echo
echo "Done."
echo "Panel: $APP_URL"
echo "Admin email: $ADMIN_EMAIL"
if [[ -z "$ADMIN_PASSWORD" ]]; then
  echo "Admin password: generated by xboard:install; check install output or run scripts/init-admin.sh"
fi
